create table product (
  product code primary key
);

insert into product values
  ('CREDIT_CARD')
, ('NEEDFUL_CREDIT_MORTGAGE')
, ('NEEDFUL_CREDIT_AUTO')
, ('NEEDFUL_CREDIT_CASH')
, ('NEEDFUL_CREDIT_PLEDGE')
, ('NEEDFUL_CREDIT_NOT_REVOLVING')
, ('NEEDFUL_CREDIT_REVOLVING')
, ('NEEDFUL_CREDIT_REFINANCING')
, ('CREDIT_DEPOSIT')
, ('AUTO_CREDIT')
;

