create table stage (
  stage code primary key
);

insert into stage values
  ('ATTRACTION')
, ('APPLICATION')
, ('VERIFICATION')
, ('PLEDGE_ESTIMATION')
, ('LEGAL_REVIEW')
, ('SECURITY')
, ('RISK_MANAGEMENT')
, ('RETAIL_COMMITTEE')
, ('CREDIT_COMMITTEE')
, ('LEGAL_REVIEW_ADDITIONAL')
, ('MIDDLE_ADMINISTRATOR')
, ('CONTRACT_SIGNING')
, ('PLEDGE_REGISTRATION')
, ('CREDIT_ADMINISTRATOR')
;

